export let actors = [
    {
        "id": 73,
        "name": "Cop Morty",
        "status": "Dead",
        "species": "Human",
        "type": "",
        "gender": "Male",
        "origin": {"name": "unknown", "url": ""},
        "location": {"name": "Citadel of Ricks", "url": "https://rickandmortyapi.com/api/location/3"},
        "image": "https://rickandmortyapi.com/api/character/avatar/73.jpeg",
        "episode": ["https://rickandmortyapi.com/api/episode/28"],
        "url": "https://rickandmortyapi.com/api/character/73",
        "created": "2017-11-30T11:43:04.217Z"
    },
    {
        "id": 252,
        "name": "Noob-Noob",
        "status": "Alive",
        "species": "Poopybutthole",
        "type": "",
        "gender": "Male",
        "origin": {"name": "unknown", "url": ""},
        "location": {"name": "Vindicator's Base", "url": "https://rickandmortyapi.com/api/location/54"},
        "image": "https://rickandmortyapi.com/api/character/avatar/252.jpeg",
        "episode": ["https://rickandmortyapi.com/api/episode/25"],
        "url": "https://rickandmortyapi.com/api/character/252",
        "created": "2017-12-31T12:57:37.849Z"
    },
    {
        "id": 529,
        "name": "Lizard",
        "status": "Dead",
        "species": "Alien",
        "type": "Lizard",
        "gender": "Male",
        "origin": {"name": "Midland Quasar", "url": "https://rickandmortyapi.com/api/location/85"},
        "location": {"name": "Midland Quasar", "url": "https://rickandmortyapi.com/api/location/85"},
        "image": "https://rickandmortyapi.com/api/character/avatar/529.jpeg",
        "episode": ["https://rickandmortyapi.com/api/episode/33"],
        "url": "https://rickandmortyapi.com/api/character/529",
        "created": "2020-05-02T13:31:49.867Z"
    },
    {
        "id": 548,
        "name": "Truckula",
        "status": "Alive",
        "species": "Mythological Creature",
        "type": "Vampire",
        "gender": "Male",
        "origin": {"name": "unknown", "url": ""},
        "location": {"name": "Heist-Con", "url": "https://rickandmortyapi.com/api/location/88"},
        "image": "https://rickandmortyapi.com/api/character/avatar/548.jpeg",
        "episode": ["https://rickandmortyapi.com/api/episode/34"],
        "url": "https://rickandmortyapi.com/api/character/548",
        "created": "2020-05-07T09:19:47.204Z"
    },
    {
        "id": 712,
        "name": "Too Cute to Murder Beth",
        "status": "Dead",
        "species": "Robot",
        "type": "Decoy",
        "gender": "Female",
        "origin": {"name": "Earth (Replacement Dimension)", "url": "https://rickandmortyapi.com/api/location/20"},
        "location": {"name": "Earth (Replacement Dimension)", "url": "https://rickandmortyapi.com/api/location/20"},
        "image": "https://rickandmortyapi.com/api/character/avatar/712.jpeg",
        "episode": ["https://rickandmortyapi.com/api/episode/43"],
        "url": "https://rickandmortyapi.com/api/character/712",
        "created": "2021-10-17T09:40:13.581Z"
    },
    {
        "id": 736,
        "name": "Spaceman",
        "status": "Dead",
        "species": "Human",
        "type": "",
        "gender": "Male",
        "origin": {"name": "Earth (Replacement Dimension)", "url": "https://rickandmortyapi.com/api/location/20"},
        "location": {"name": "Space", "url": "https://rickandmortyapi.com/api/location/115"},
        "image": "https://rickandmortyapi.com/api/character/avatar/736.jpeg",
        "episode": ["https://rickandmortyapi.com/api/episode/45"],
        "url": "https://rickandmortyapi.com/api/character/736",
        "created": "2021-10-17T12:11:21.171Z"
    }
]